language: node_js

cache:
  directories:
  - node_modules

node_js:
  - stable
  - iojs

matrix:
  allow_failures:
    - node_js: iojs
  include:
    - node_js: 5.3
      env: SENDCOVERAGE=1

after_script:
  - if [ $SENDCOVERAGE ]; then ./coverage-calc.sh; ./coverage-send.sh && rm -rf ./coverage; fi
