# Sync volebo.net with ekbvolley.com

# Copyright (C) 2016  Volebo <volebo.net@gmail.com>
# Copyright (C) 2016  Koryukov Maksim <maxkoryukov@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the MIT License, attached to this software package.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# You should have received a copy of the MIT License along with this
# program. If not, see <https://opensource.org/licenses/MIT>.

# http://spdx.org/licenses/MIT

sudo: false

language: node_js

node_js:
  - 6

# env:
#  global:
#    - NODE_ENV=dev

# matrix:
#  allow_failures:
#    - node_js: 4

cache:
  directories:
  - node_modules

before_install:
  - npm config set spin false

install:
  - npm install
  - npm install -g codecov
  - npm install -g bithound

script:
  - npm run lint
  - npm test
  - npm run coverage
  - codecov
  - bithound check git@github.com:$TRAVIS_REPO_SLUG.git

deploy:
  provider: npm
  api_key:
    secure: "S/A9UN46gr/xsmKmaKpwiwMtN8ESST5IhQkoaFn0kOB3+Xf9F3J5mirdm32rjc+BX1eR9DkgsOunclXIR3C48hos9N13aVpRdGORfzxT4coTPoW4XG1047AKIwwuWgzhhD7bjpi0vT/0G68XWQKLSb5RRQrcfbS0mhhkvjfzCpu4g2LGdbdXTiygjhsI0GUAGn45Fsk45uWvUUlgMTYYNRGwb+WBkNkbGwNOL5q7EEFTFqppXiqQJ/N1rSqVLf0j8gNTTVPonKuliB6o2OXzQugC8ZDKRibX/ihUKn4v/0DC1BnYBggek8U+XxlPZURTrX+6mbg4WYm8dB4x96EXET5ijl32s0xJ1KRtD4o7JT/vpIA74vS72BdqoSYp6hGS1ex1Do+oLP0FgBd0PQczGjlec9RjkSc1KRs+YqzUoM8RMjWGlsF5jrWMuFiKuhpMs0jAdIMcImyfrprJ2BjiJXwi3Uf+oobXuunuiy2qlCfYFRA4TDMJlGIVoBbFazE3MeSzJb3Uo86ySv+dS/0adlYKFb7riNOqVzwxyli3rsXGxD6jyLFU+QLV5taHY8TFuKo8Ne2yd3dLXMKWurzjVZGC+Yk8Q9nIkan3mKKmndwsdaF9UXL/TN4Ok2VH+R5xdpr1huqxYy7rLvYjyJ67zVVGHrfA/7QbY/HOjVtD4C0="
  email: dev@volebo.net
  on:
    tags: true
    node: 6
    repo: volebo/import-ekbvolley

after_deploy:
  # Send notification to Slack:
  - curl -sL https://raw.githubusercontent.com/volebo/dev/master/scripts/im/slack-publish.sh | bash -s -
