language: node_js

cache:
  directories:
  - node_modules

node_js:
  - "0.12"
  - "iojs"

matrix:
  include:
    - node_js: "5.3"
      env: SENDCOVERAGE=1

after_script:
  - istanbul cover _mocha --report lcovonly -- --recursive  -R spec test/*.js
  - if [ $SENDCOVERAGE ]; then ./coverage-calc.sh; ./coverage-send.sh && rm -rf ./coverage; fi
